# Generated by Django 5.0.4 on 2024-04-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_booking', models.BooleanField(blank=True, default=0)),
                ('no_min_booking', models.BooleanField(blank=True, default=0)),
                ('projector', models.BooleanField(blank=True, default=0)),
                ('payment_by_organizer', models.BooleanField(blank=True, default=0)),
                ('mastermind', models.BooleanField(blank=True, default=0)),
                ('rhetoric', models.BooleanField(blank=True, default=0)),
                ('poufs', models.BooleanField(blank=True, default=0)),
                ('flipchart', models.BooleanField(blank=True, default=0)),
                ('laptop', models.BooleanField(blank=True, default=0)),
                ('coaching_rate', models.BooleanField(blank=True, default=0)),
                ('tea_rate', models.BooleanField(blank=True, default=0)),
                ('coffee_rate', models.BooleanField(blank=True, default=0)),
                ('birthday', models.BooleanField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('room', models.CharField(choices=[('Кабинет', 'Кабинет'), ('Каминная', 'Каминная'), ('Большой зал', 'Большой зал'), ('Полосатая', 'Полосатая'), ('Лето', 'Лето'), ('Осень', 'Осень'), ('Зима', 'Зима'), ('Весна', 'Весна'), ('Бордовая', 'Бордовая'), ('Мансардная', 'Мансардная'), ('Бирюзовая', 'Бирюзовая')], max_length=11, verbose_name='Комната')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=15)),
                ('how_many_visitors', models.IntegerField()),
                ('start_time', models.TimeField(verbose_name='Начало бронирования')),
                ('end_time', models.TimeField(verbose_name='Конец бронирования')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='booking.tags', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Запись о бронировании',
                'verbose_name_plural': 'Записи о бронировании',
            },
        ),
    ]
