# Generated by Django 5.0.4 on 2024-04-12 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
