# Generated by Django 4.2.11 on 2024-03-26 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_booking', models.BooleanField(default=0)),
                ('no_min_booking', models.BooleanField(default=0)),
                ('projector', models.BooleanField(default=0)),
                ('payment_by_organizer', models.BooleanField(default=0)),
                ('mastermind', models.BooleanField(default=0)),
                ('rhetoric', models.BooleanField(default=0)),
                ('poufs', models.BooleanField(default=0)),
                ('flipchart', models.BooleanField(default=0)),
                ('laptop', models.BooleanField(default=0)),
                ('coaching_rate', models.BooleanField(default=0)),
                ('tea_rate', models.BooleanField(default=0)),
                ('coffee_rate', models.BooleanField(default=0)),
                ('birthday', models.BooleanField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='tags',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='booking.tags'),
        ),
    ]
