# Generated by Django 4.2.11 on 2024-03-28 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_tags_alter_booking_date_booking_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tags',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book', to='booking.tags'),
        ),
    ]
