# Generated by Django 5.0.4 on 2024-04-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_tags_booking_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.RemoveField(
            model_name='tags',
            name='slug',
        ),
        migrations.AddField(
            model_name='tags',
            name='meaning',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='booking.tags', verbose_name='Тэги'),
        ),
    ]
