# Generated by Django 4.2.11 on 2024-04-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='birthday',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='coaching_rate',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='coffee_rate',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='flipchart',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='laptop',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='mastermind',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='min_booking',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='no_min_booking',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='payment_by_organizer',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='poufs',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='projector',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='rhetoric',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tea_rate',
            field=models.BooleanField(blank=True, default=0),
        ),
    ]
