# Generated by Django 5.0.4 on 2024-04-13 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_rooms_alter_booking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.rooms', verbose_name='Комната'),
        ),
    ]
