# Generated by Django 5.0.4 on 2024-04-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='floor',
            field=models.CharField(choices=[(1, '1 этаж'), (2, '2 этаж')], db_index=True, max_length=1, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='how_many_visitors',
            field=models.IntegerField(verbose_name='Количество посетителей'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Номер телефона'),
        ),
    ]
