# Generated by Django 5.0.4 on 2024-04-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_remove_rooms_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='floor',
            field=models.IntegerField(blank=True, max_length=2, null=True, verbose_name='Этаж'),
        ),
    ]
