# Generated by Django 5.0.4 on 2024-05-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_rooms_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='description',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Описание комнаты'),
        ),
    ]
